### ISSUE TITLE
Dummy road in Burns' mansion backyard

### ISSUE THREAD

**Issue by AdelaideIreneline** [donutteam/project-donut-anniversary-edition#42]
Add a dummy road to the backyard of Mr. Burns' mansion so that getting a Hit & Run there (thanks to the props and Lucas' ambient character) doesn't have any chance of breaking the music due to no vehicles spawning.

**Comment by duckdotapk** [comment]
Fixed instead with a big ass trigger that prevents you from getting Hit & Runs in this area.
